### ISSUE TITLE
Params are not encoded in OAuth url

### ISSUE THREAD

**Issue by danielhoey** [woothemes/wc-api-ruby#1]
The params in the url returned by OAuth::get_oauth_url are not encoded. This causes a problem (in particular) if the generated signature contains characters such as '+'. In this case the authentication with wooCommerce will fail as it expects '+' to be encoded as '%2B'.

I think that line 40 in woocommerce_api/oauth.rb should be something like this:

    query_string = URI::encode(params.map{|key, value| "#{key}=#{CGI::escape(value.to_s)}"}.join("&"))

Probably the keys should be encoded also.

**Comment by claudiosmweb** [comment]
Please submit a Pull Request.
