### ISSUE TITLE
Trouble creating coupon, provided signature does not match

### ISSUE THREAD

**Issue by Datise** [woothemes/wc-api-ruby#13]
Trying to create a coupon on a wordpress site through my api but getting this issue: 
{"errors"=>[{"code"=>"woocommerce_api_authentication_error", "message"=>"Invalid Signature - provided signature does not match"}]}
The wordpress site is still being built and does not have https, and I can't even find where the "pretty permalinks" option is.
wp version: 4.3.1
woocomm version: 2.4.10
server is apache
php version is 
initializing with the same as explained in setup section of the readme with no args.
I have tried revoking Api consumer secrete and key and placing new ones in to no change. 

This was all working a month ago or so but it hasn't been used since..not sure what the difference is now.
Any thoughts? pretty terrible with wordpress so apologies in advance if this is a basic config problem.

**Comment by claudiosmweb** [comment]
Here is not a support channel and seems like it is not a bug... Please check or documentation: http://woothemes.github.io/woocommerce-rest-api-docs/
