### ISSUE TITLE
EOFError

### ISSUE THREAD

**Issue by kbacha** [woothemes/wc-api-ruby#20]
Getting an EOFError on products with over 100 variations. It appears to partially create the listing in woo but then breaks on the gem side. Any ideas what it might be from?

**Comment by kbacha** [comment]
Best I can tell is that there is some poorly configured timeout on their server and it's returning a body that is shorter than the content-length.

Could only partially confirm this with Curl though (as I might have measured the length of the body wrong).

Anyhow, this appears to be a customer configuration issue. Gonna close.

**Comment by claudiosmweb** [comment]
> poorly configured timeout on their server and it's returning a body that is shorter than the content-length

I was thinking about it during the day. I was to tell you it was some timeout problem.
