### ISSUE TITLE
update customer role

### ISSUE THREAD

**Issue by TeamOussama** [woothemes/wc-api-ruby#22]
i try this api with status update and get orders and customers and its work well.
but when i come to update customer role its not updating !! i use next code:

 data={
          "customer" => {
              "role" => "Editor"
          }
      }
      puts woocommerce.put("customers/3", data)

**Comment by claudiosmweb** [comment]
`role` is read-only, not possible to update.

**Comment by TeamOussama** [comment]
where i can find this information please in documentation !!
and can i update group of customers ?

thank you claudiosmweb!!

**Comment by claudiosmweb** [comment]
@TeamOussama here is not a support forum.
