### ISSUE TITLE
API generates 'Consumer Key is missing'

### ISSUE THREAD

**Issue by kbacha** [woothemes/wc-api-ruby#5]
We ran into this with our own implementation of an API wrapper and I though that using this gem would "fix" it but no luck :(.

When using v2, the api spits back "Consumer Key is missing" on some servers.

This is documented in the API:

> Occasionally some servers may not properly parse the Authorization header (if you see a “Consumer key is missing” error when authenticating over SSL, you have a server issue). In this case, you may provide the consumer key/secret as query string parameters.

I'm not sure what "you have a server issue" is but since this is a customer of ours that is running into it, we don't have direct access to their server to see what the issue is. Is there any way that this gem could realize that this has happened and fallback to the query string params?

**Comment by kbacha** [comment]
Got this working on my fork by passing the consumer key and secret into the query string of the request. Going to write up a pull request for this as well.

**Comment by claudiosmweb** [comment]
You can use `?consumer_key=user&consumer_secret=pass` on the end of your URL.
But this is not work for API version 3.
This happens only on outdated servers.

**Comment by kbacha** [comment]
@claudiosmweb What is going to be the methodology in version 3? Currently the online documentation for v3 says that it works.

http://woothemes.github.io/woocommerce-rest-api-docs/#authentication

**Comment by claudiosmweb** [comment]
@kbacha I'll remove it soon.

**Comment by kbacha** [comment]
@claudiosmweb Ok, I feel a little in the dark here. Would you be willing to provide me some more details on how auth will work going forward and how we can continue to support any backward compatibility for our customers?

Requiring a customer to upgrade your product so that they can use ours seems like pushing an undue burden onto application developers and your customers. If there are different means of auth based on different versions, then it stands to reason that the client gem that you put out needs to backward support them (especially if it continues to supports the older versions).

We, at Sellbrite, need to be able to support several different versions and I was hoping that the gem put out by woocommerce would provide the backward functionality to help us with a smooth development process and make our lives easier. If I need to hack the query params for every customer outside of the client gem, then my life is harder, not easier.

**Comment by claudiosmweb** [comment]
Because v3 implement full basic authentication ([conforms to the Basic auth spec](http://tools.ietf.org/html/rfc2617)).

**Comment by shingara** [comment]
This issue is still going. See the woocommerce documentation : 


https://woothemes.github.io/woocommerce-rest-api-docs/?ruby#authentication

> Occasionally some servers may not parse the Authorization header correctly (if you see a “Consumer key is missing” error when authenticating over SSL, you have a server issue). In this case, you may provide the consumer key/secret as query string parameters.
